# This Docker Compose file is dedicated SOLELY to running the benchmark experiment.
# It overrides entrypoints and sets environment variables for service discovery.
services:
  # --- Application Services Under Test ---
  dropper:
    build: ../src/dropper
    entrypoint: python main.py
    ports:
      - "5000:5000"
    environment:
      - DECRYPTER_URL=http://decrypter:5000/decrypt
      - FAULT_DETECTOR_URL=http://fault-detector:5000/data
    depends_on:
      - decrypter
      - fault-detector

  decrypter:
    build: ../src/decrypter
    entrypoint: python main.py
    environment:
      - FAULT_DETECTOR_URL=http://fault-detector:5000/data
    depends_on:
      - fault-detector
  
  fault-detector:
    build: ../src/fault-detector
    entrypoint: python main.py
    environment:
      - DIGITAL_TWIN_URL=http://digital-twin:5000/update
    depends_on:
      - digital-twin

  digital-twin:
    build: ../src/digital-twin
    entrypoint: python main.py
    ports:
      - "5001:5000"
  
  # --- Benchmark Runner Service ---
  benchmark:
    build: .
    depends_on:
      - dropper
    volumes:
      - ./results:/app/results