# This Docker Compose file is dedicated SOLELY to running the benchmark experiment.
# It defines the minimum required application stack plus the benchmark service itself.
services:
  # --- Application Services Under Test ---
  dropper:
    build: ../src/dropper # Path relative to this file's location
    entrypoint: python main.py
    ports:
      - "5000:5000"
    environment:
      - DECRYPTER_URL=http://decrypter:5000/decrypt
      - FAULT_DETECTOR_URL=http://fault-detector:5000/data
      - POISSON_LAMBDA=0.1
    depends_on:
      - decrypter
      - fault-detector

  decrypter:
    build: ../src/decrypter
    entrypoint: python main.py
    environment:
      - FAULT_DETECTOR_URL=http://fault-detector:5000/data
    depends_on:
      - fault-detector
  
  fault-detector:
    build: ../src/fault-detector
    entrypoint: python main.py
    environment:
      - DIGITAL_TWIN_URL=http://digital-twin:5000/update
    depends_on:
      - digital-twin

  digital-twin:
    build: ../src/digital-twin
    entrypoint: python main.py
    ports:
      - "5001:5000"
  
  # NOTE: 'production-line-1' is not included because the 'benchmark'
  # service acts as the data producer for this test.

  # --- Benchmark Runner Service ---
  benchmark:
    # Build context is the current directory ('.') where the Dockerfile resides
    build: .
    depends_on:
      - dropper
    # Mount the local 'results' directory into the container
    volumes:
      - ./results:/app/results