# Start with: "kathara lstart --noterminals && kathara connect --logs p1 && kathara lclean"

# Lab Metadata
LAB_NAME="IIoT-sim-REST"
LAB_DESCRIPTION="REST-based version of the IIoT simulator on Kathara"
LAB_VERSION=7.3
LAB_AUTHOR="Filippo Lucchesi"
LAB_EMAIL="filippo@lucchesi.eu"

# Images
# Intermediaries
int1[image]="kathara/base"
int2[image]="kathara/base"
int3[image]="kathara/base"
int4[image]="kathara/base"

# Active agents
dropper[image]="fillol/iiot-kathara-dropper"
decrypter[image]="fillol/iiot-kathara-decrypter"
faultdetector[image]="fillol/iiot-kathara-fault-detector"
digitaltwin[image]="fillol/iiot-kathara-digital-twin"
p1[image]="fillol/iiot-kathara-publisher1"

# Networks
# Producers to int1
p1[0]=net_p1
int1[1]=net_p1

# Bridge between decrypter int1 and int2
int1[0]=br_12
int2[0]=br_12

# Path from int2 to Dropper
int2[1]=net_main_in
dropper[0]=net_main_in

# Standard Path: Dropper -> int2 -> int3 -> faultdetector
int2[2]=br_23
int3[0]=br_23
int3[1]=net_fd_standard
faultdetector[0]=net_fd_standard

# Secure Path: Dropper -> decrypter -> int4 -> faultdetector
dropper[1]=net_drop_dec
decrypter[0]=net_drop_dec
decrypter[1]=net_dc_out
int4[0]=net_dc_out
int4[1]=net_fd_secure
faultdetector[1]=net_fd_secure

# Final Path: faultdetector -> digitaltwin
faultdetector[2]=net_fd_dt
digitaltwin[0]=net_fd_dt

# Network Diagram
#        [p1]
#         | (net_p1)
#       [int1]
#         | (br_12)
#       [int2] ------------------------+
#         |                            | (net_main_in)
#         | (br_23)                [dropper]
#         |                            | (net_drop_dec)
#       [int3]                     [decrypter]
#         |                            | (net_dc_out)
#         | (net_fd_standard)        [int4]
#         |                            | (net_fd_secure)
#         +------ [faultdetector] -----+
#                       |
#                       | (net_fd_dt)
#                       |
#                 [digitaltwin]