LAB_NAME="IIoTsim-Nobel-Germany"
LAB_DESCRIPTION="Rete basata sulla topologia Nobel Germany"
LAB_VERSION="1.0"
LAB_AUTHOR="Filippo Lucchesi"
LAB_EMAIL="filippo@lucchesi.eu"



# Images

berlin[image]="kathara/base"
hamburg[image]="kathara/base"
duesseldorf[image]="kathara/base"
hannover[image]="kathara/base"
karlsruhe[image]="kathara/base"
nuernberg[image]="kathara/base"
muenchen[image]="kathara/base"
norden[image]="kathara/base"
bremen[image]="kathara/base"
leipzig[image]="kathara/base"
frankfurt[image]="kathara/base"
dortmund[image]="kathara/base"
stuttgart[image]="kathara/base"
ulm[image]="kathara/base"
mannheim[image]="kathara/base"
koeln[image]="kathara/base"
essen[image]="kathara/base"


# Interfaces Configuration

# A: Norden - Bremen
# B: Norden - Dortmund
# C: Bremen - Hamburg
# D: Bremen - Hannover
# E: Hamburg - Hannover
# F: Hamburg - Berlin
# G: Hannover - Berlin
# H: Hannover - Leipzig
# I: Hannover - Frankfurt
# J: Hannover - Dortmund
# K: Berlin - Leipzig
# L: Leipzig - Frankfurt
# M: Leipzig - Nuernberg
# N: Nuernberg - Frankfurt
# O: Nuernberg - Stuttgart
# P: Nuernberg - Muenchen
# Q: Muenchen - Ulm
# R: Ulm - Stuttgart
# S: Stuttgart - Karlsruhe
# T: Karlsruhe - Mannheim
# U: Mannheim - Frankfurt
# V: Frankfurt - Koeln
# W: Koeln - Duesseldorf
# X: Duesseldorf - Essen
# Y: Essen - Dortmund
# Z: Dortmund - Koeln

norden[0]="A"
norden[1]="B"

bremen[0]="A"
bremen[1]="C"
bremen[2]="D"

hamburg[0]="C"
hamburg[1]="E"
hamburg[2]="F"

hannover[0]="D"
hannover[1]="E"
hannover[2]="G"
hannover[3]="H"
hannover[4]="I"
hannover[5]="J"

berlin[0]="F"
berlin[1]="G"
berlin[2]="K"

leipzig[0]="H"
leipzig[1]="K"
leipzig[2]="L"
leipzig[3]="M"

nuernberg[0]="M"
nuernberg[1]="N"
nuernberg[2]="O"
nuernberg[3]="P"

muenchen[0]="P"
muenchen[1]="Q"

ulm[0]="Q"
ulm[1]="R"

stuttgart[0]="O"
stuttgart[1]="R"
stuttgart[2]="S"

karlsruhe[0]="S"
karlsruhe[1]="T"

mannheim[0]="T"
mannheim[1]="U"

frankfurt[0]="I"
frankfurt[1]="L"
frankfurt[2]="N"
frankfurt[3]="U"
frankfurt[4]="V"

koeln[0]="V"
koeln[1]="W"
koeln[2]="Z"

duesseldorf[0]="W"
duesseldorf[1]="X"

essen[0]="X"
essen[1]="Y"

dortmund[0]="B"
dortmund[1]="J"
dortmund[2]="Y"
dortmund[3]="Z"